[dashboard]
display_controller = 'waveshare_epaper'
weather_provider = 'openweather'
# weather_provider = 'accuweather'
calendar_provider = 'google'

lat_long = "40.6976307,-74.1448279"
unit_type = 'imperial'
quiet_hours = [0, 1, 2, 3, 4, 5]
time_zone = "America/New_York"
debug_mode = false

[accuweather]
api_key =  "abc123"
language = "en-us"

[openweather]
api_key = "abc123"
language = "en"

[waveshare_epaper]
model = 'epd7in5_v2'

[nws]
user_agent = "(weather-dashboard, myemail@email.com)"